---
- name: Add mongodb repo on {{ ansible_distribution }}
  include: mongodb_{{ ansible_pkg_mgr }}.yaml
  tags: [databases, mongodb]

- name: Install mongodb
  become: yes
  package:
    name: mongodb-org
    # Try to upgrade the package just in case if user changed the major version
    state: "{{ 'latest' if mongodb_repo_add.changed or 'present' }}"
  notify:
    - restart mongod
  tags: [databases, mongodb]

- name: Start & Enable mongodb
  become: yes
  service:
    name: mongod
    state: started
    enabled: yes
  tags: [databases, mongodb]
