---
- name: Install mongodb rhel
  include: mongodb_rhel.yaml
  when: ansible_distribution == 'CentOS'

- name: Install mongodb deb
  include: mongodb_deb.yaml
  when: ansible_distribution == 'Ubuntu'
