---
- name: apt | Add mongodb key
  become: yes
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-{{ mongodb_major_minor_version }}.asc
    state: present
  tags: [databases, mongodb]

- name: apt | Add mongodb repository
  become: yes
  apt_repository:
    repo: 'deb http://repo.mongodb.org/apt/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }}/mongodb-org/{{ mongodb_major_minor_version }} multiverse'
    state: present
  tags: [databases, mongodb]

- name: apt | Install mongodb
  become: yes
  apt:
    name: mongodb-org={{ mongodb_version }}*
    state: present
  notify: Restart mongod
  tags: [databases, mongodb]
