---
- name: apt | Add mongodb key
  become: yes
  apt_key:
    keyserver: "hkp://keyserver.ubuntu.com:80"
    id: 0C49F3730359A14518585931BC711F9BA15703C6
    state: present
  tags: [databases, mongodb]

- name: apt | Add mongodb repository
  become: yes
  apt_repository:
    repo: 'deb http://repo.mongodb.org/apt/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }}/mongodb-org/3.4 multiverse'
    state: present
  register: mongodb_repo_add
  tags: [databases, mongodb]

- name: apt | Install mongodb
  become: yes
  apt:
    name: mongodb-org
    state: "{{ 'latest' if mongodb_repo_add.changed or 'present' }}"
  notify: restart mongod
  tags: [databases, mongodb]
