---
- include: mongodb_rhel6_dependencies.yaml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

- name: Add mongodb key
  become: yes
  rpm_key:
    key: https://www.mongodb.org/static/pgp/server-3.2.asc
    state: present
  tags: [databases, mongodb]

- name: Add mongodb repository
  become: yes
  yum_repository:
    name: mongodb-org-3.2
    description: MongoDB Repository
    gpgcheck: yes
    enabled: yes
    baseurl: https://repo.mongodb.org/yum/redhat/{{ ansible_distribution_major_version }}Server/mongodb-org/3.2/x86_64/
    gpgkey: https://www.mongodb.org/static/pgp/server-3.2.asc
    state: present
  tags: [databases, mongodb]

- name: Install mongodb
  become: yes
  yum:
    name: mongodb-org
    update_cache: yes
    state: present
  notify:
    - enable mongodb rhel 7
    - restart mongodb
    - chkconfig mongod on rhel 6
  tags: [databases, mongodb]
