---
- include: mongodb_rhel_dependencies.yaml

- name: yum | Add mongodb key
  become: yes
  rpm_key:
    key: https://www.mongodb.org/static/pgp/server-{{ mongodb_major_minor_version }}.asc
    state: present
  tags: [databases, mongodb]

- name: yum | Add mongodb repository
  become: yes
  yum_repository:
    name: mongodb-org-3.4
    description: MongoDB Repository
    gpgcheck: yes
    enabled: yes
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{ mongodb_major_minor_version }}/x86_64/
    gpgkey: https://www.mongodb.org/static/pgp/server-{{ mongodb_major_minor_version }}.asc
    state: present
  tags: [databases, mongodb]

- name: yum | Install mongodb
  become: yes
  yum:
    name: mongodb-org-{{ mongodb_version }}*
    state: present
  notify:
    - Restart mongod
  tags: [databases, mongodb]
