---
- name: enable mongodb rhel 7
  become: yes
  systemd:
    name: mongod
    enabled: yes
    state: started
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: restart mongodb
  become: yes
  service:
    name: mongod
    state: restarted

- name: chkconfig mongod on rhel 6
  become: yes
  command: chkconfig mongod on
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'
